services:
  - type: web
    name: n8n-elev8
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.nmvdzjyfoxwfylaziydt
      - key: DB_POSTGRESDB_PASSWORD
        value: Meli2020.
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Meli2020.
      - key: N8N_ENCRYPTION_KEY
        value: Meli2020.
      - key: WEBHOOK_URL
        value: https://n8n-elev8.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-elev8.onrender.com
      - key: N8N_HOST
        value: n8n-elev8.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
